name: Update Matches Daily
on:
  schedule:
    - cron: '0 */6 * * *'  # كل 6 ساعات
  workflow_dispatch:  # تشغيل يدوي

jobs:
  update-matches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update matches data
        run: |
          curl -X GET "https://v3.football.api-sports.io/fixtures?date=$(date +%Y-%m-%d)" \
          -H "x-rapidapi-key: ${{ secrets.API_FOOTBALL_KEY }}" \
          -H "x-rapidapi-host: v3.football.api-sports.io" \
          -o matches.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add matches.json
          git commit -m "Update matches data" || exit 0
          git push
