name: Update Matches JSON

on:
  schedule:
    - cron: '0 1 * * *'   # مرة يومياً 01:00 UTC
  workflow_dispatch:        # تشغيل يدوي من GitHub

permissions:
  contents: write   # مهم لإعطاء صلاحية الكتابة

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run fetch-matches.js
        env:
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: node fetch-matches.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add matches.json
          git diff --staged --quiet || git commit -m "chore: update matches.json (automated)"
          git push
