name: Update Matches Data
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-matches:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Update matches data
      env:
        API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      run: |
        python -c "
import requests
import json
import os
from datetime import datetime, timedelta

api_key = os.getenv('API_KEY')
headers = {
    'x-rapidapi-key': api_key,
    'x-rapidapi-host': 'v3.football.api-sports.io'
}

def get_matches(date):
    url = f'https://v3.football.api-sports.io/fixtures?date={date}'
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            return response.json()
        else:
            print(f'Error for {date}: {response.status_code}')
            return {'response': []}
    except Exception as e:
        print(f'Exception for {date}: {e}')
        return {'response': []}

# Get dates
today = datetime.now().strftime('%Y-%m-%d')
yesterday = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
tomorrow = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d')

print('Fetching matches...')

# Get matches for all three days
all_matches = []
for date in [yesterday, today, tomorrow]:
    data = get_matches(date)
    if 'response' in data:
        all_matches.extend(data['response'])
    print(f'Found {len(data.get(\"response\", []))} matches for {date}')

# Save to file
output = {'response': all_matches}
with open('matches.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f'Total matches: {len(all_matches)}')
print('matches.json updated successfully!')
"

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add matches.json
        git diff --staged --quiet || git commit -m "🤖 Auto-update matches - $(date +'%Y-%m-%d %H:%M')"
        git push
